import localFont from "next/font/local";
import "./global.css";
import { ReactNode } from "react"; 

// Definindo as fontes
const geistSans = localFont({
  src: "./font/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./font/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Definindo o metadata (opcional)
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Definindo o tipo das props
interface RootLayoutProps {
  children: ReactNode; // children pode ser qualquer nó React válido
}

// Componente de layout principal
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
